//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderToDrawing.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
<<<<<<< HEAD
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
=======
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0")]
>>>>>>> a25158f (Initial commit)
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
<<<<<<< HEAD
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Temp\\")]
=======
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\WIPFIL02\\InforLNTest\\ACAD\\Seriennummernfiles\\")]
>>>>>>> a25158f (Initial commit)
        public string CSVSearchingPath {
            get {
                return ((string)(this["CSVSearchingPath"]));
            }
            set {
                this["CSVSearchingPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
<<<<<<< HEAD
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Temp\\")]
=======
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\WIPFIL02\\InforLNTest\\ACAD\\BestellskizzenNeu\\")]
>>>>>>> a25158f (Initial commit)
        public string DWGOutputPath {
            get {
                return ((string)(this["DWGOutputPath"]));
            }
            set {
                this["DWGOutputPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
<<<<<<< HEAD
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Temp\\")]
=======
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\wiptcr05\\sbomi\\dwg\\")]
>>>>>>> a25158f (Initial commit)
        public string DWGSearchingPath {
            get {
                return ((string)(this["DWGSearchingPath"]));
            }
            set {
                this["DWGSearchingPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
<<<<<<< HEAD
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Temp\\")]
=======
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\WIPFIL02\\InforLNTest\\ACAD\\Archiv\\")]
>>>>>>> a25158f (Initial commit)
        public string CSVOutputPath {
            get {
                return ((string)(this["CSVOutputPath"]));
            }
            set {
                this["CSVOutputPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
<<<<<<< HEAD
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Temp\\")]
=======
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\wiptcr05\\sbomi\\dwg\\")]
>>>>>>> a25158f (Initial commit)
        public string PDSSearchingPath {
            get {
                return ((string)(this["PDSSearchingPath"]));
            }
            set {
                this["PDSSearchingPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
<<<<<<< HEAD
        [global::System.Configuration.DefaultSettingValueAttribute("ra_ra*,test_*")]
=======
        [global::System.Configuration.DefaultSettingValueAttribute("ra_ra*,ra_ga*,stahl_aus_trep*,wcbox_RAHM*,terr_ra_*,basic_ra_*,stahl_treppencont*" +
            ",tholz_ra_*,pl_ra*")]
>>>>>>> a25158f (Initial commit)
        public string SerialBlocks {
            get {
                return ((string)(this["SerialBlocks"]));
            }
            set {
                this["SerialBlocks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
<<<<<<< HEAD
        [global::System.Configuration.DefaultSettingValueAttribute("")]
=======
        [global::System.Configuration.DefaultSettingValueAttribute("183_CNR,0001_CNR")]
>>>>>>> a25158f (Initial commit)
        public string SerialAtts {
            get {
                return ((string)(this["SerialAtts"]));
            }
            set {
                this["SerialAtts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EventCounter {
            get {
                return ((int)(this["EventCounter"]));
            }
            set {
                this["EventCounter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
<<<<<<< HEAD
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Temp\\Test.scr")]
=======
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\wipfil32\\Process\\PDS\\bat\\ctx_pds_bs_infor.scr")]
>>>>>>> a25158f (Initial commit)
        public string ScriptFile {
            get {
                return ((string)(this["ScriptFile"]));
            }
            set {
                this["ScriptFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
<<<<<<< HEAD
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Temp\\")]
=======
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\wiptcr05\\sbomi\\log\\DWGtoOrderDWG\\")]
>>>>>>> a25158f (Initial commit)
        public string ErrorPath {
            get {
                return ((string)(this["ErrorPath"]));
            }
            set {
                this["ErrorPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
<<<<<<< HEAD
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
=======
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
>>>>>>> a25158f (Initial commit)
        public bool LogFileMode {
            get {
                return ((bool)(this["LogFileMode"]));
            }
            set {
                this["LogFileMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HeaderMode {
            get {
                return ((bool)(this["HeaderMode"]));
            }
            set {
                this["HeaderMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LC*")]
        public string NoPDSArtikel {
            get {
                return ((string)(this["NoPDSArtikel"]));
            }
            set {
                this["NoPDSArtikel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
<<<<<<< HEAD
        [global::System.Configuration.DefaultSettingValueAttribute("H:\\Offert-Bestellwesen\\Bestellskizzen\\InforLN\\")]
=======
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\shw04c\\ContainexTechnik\\Offert-Bestellwesen\\Bestellskizzen\\InforLN\\")]
>>>>>>> a25158f (Initial commit)
        public string DWGOrderCopyPath {
            get {
                return ((string)(this["DWGOrderCopyPath"]));
            }
            set {
                this["DWGOrderCopyPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
<<<<<<< HEAD
        [global::System.Configuration.DefaultSettingValueAttribute("MB*,IN*")]
=======
        [global::System.Configuration.DefaultSettingValueAttribute("MB*,IG*")]
>>>>>>> a25158f (Initial commit)
        public string IgnoreArtikel {
            get {
                return ((string)(this["IgnoreArtikel"]));
            }
            set {
                this["IgnoreArtikel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("*")]
        public string NamingRule {
            get {
                return ((string)(this["NamingRule"]));
            }
            set {
                this["NamingRule"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("X")]
        public string NamingRuleIgnore {
            get {
                return ((string)(this["NamingRuleIgnore"]));
            }
            set {
                this["NamingRuleIgnore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
<<<<<<< HEAD
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Temp\\Test.scr")]
=======
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\wipfil32\\Process\\PDS\\bat\\ctx_pds_bs_infor_end.scr")]
>>>>>>> a25158f (Initial commit)
        public string ScriptFile2 {
            get {
                return ((string)(this["ScriptFile2"]));
            }
            set {
                this["ScriptFile2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Plot {
            get {
                return ((bool)(this["Plot"]));
            }
            set {
                this["Plot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
<<<<<<< HEAD
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\wipfil32\\CTXSR\\OrderToDrawing\\user.config")]
=======
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\wiptcr05\\sbomi\\updated\\")]
        public string JsonSearchingPath {
            get {
                return ((string)(this["JsonSearchingPath"]));
            }
            set {
                this["JsonSearchingPath"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DBAG92;Initial Catalog=MW_TC_LN_Interface;Integrated Security=True")]
        public string MW_TC_LN_InterfaceConnectionString {
            get {
                return ((string)(this["MW_TC_LN_InterfaceConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DBAG92;Initial Catalog=MW_TC_LN_Interface;Integrated Security=True")]
        public string ConnectionString {
            get {
                return ((string)(this["ConnectionString"]));
            }
            set {
                this["ConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WITILN07\\informig;Initial Catalog=MW_TC_LN_Interface;Integrated Secur" +
            "ity=True")]
        public string MW_TC_LN_InterfaceConnectionString1 {
            get {
                return ((string)(this["MW_TC_LN_InterfaceConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=dbag92;Integrated Security=True")]
        public string DataSourceConnectionString {
            get {
                return ((string)(this["DataSourceConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\wipfil32\\CTXSR\\OrderToDrawingCOIN\\user.config")]
>>>>>>> a25158f (Initial commit)
        public string ConfigPath {
            get {
                return ((string)(this["ConfigPath"]));
            }
            set {
                this["ConfigPath"] = value;
            }
        }
<<<<<<< HEAD
=======
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ObjectIdentificatorAsBlock {
            get {
                return ((bool)(this["ObjectIdentificatorAsBlock"]));
            }
            set {
                this["ObjectIdentificatorAsBlock"] = value;
            }
        }
>>>>>>> a25158f (Initial commit)
    }
}
