// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderToDrawing.Models;

public partial class ACAD_SerialNumber
{
    public string PO_Number { get; set; }

    public string PO_Position { get; set; }

    public string Item_Id { get; set; }

    public string Drawing_No { get; set; }

    public string SO_Position { get; set; }

    public string PO_Sequence { get; set; }

    public string SerialNumber { get; set; }

    public string Status { get; set; }

    public DateTime? Timestamp { get; set; }
}