// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderToDrawing.Models;

public partial class ACAD_TC_Imports
{
    public string Task { get; set; }

    public string PO_Number { get; set; }

    public string Drawing_Number { get; set; }

    public string Status { get; set; }

    public DateTime Create_DateTime { get; set; }

    public DateTime? Update_DateTime { get; set; }
}