// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderToDrawing.Models;

public partial class ACAD_GroupIdentificator
{
    public string Status { get; set; }

    public string ACAD_DrawingNo { get; set; }

    public string PO_Number { get; set; }

    public string TC_SolutionID { get; set; }

    public string Group_Identificator { get; set; }

    public DateTime? created { get; set; }

    public DateTime? modified { get; set; }
}